name: Minimal theme
description: Minimal is a theme for GitHub Pages.
theme: jekyll-theme-minimal 
markdown: kramdown
google_analytics: UA-56515654-4

gems:
  - jekyll-sitemap
  
gem "github-pages", group: :jekyll_plugins


